using System;
using System.Buffers.Binary;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Pando.SerializerGenerator.Utils;

namespace Pando.SerializerGenerator;

public static class GeneratedSerializerRenderer
{
	public static SourceText Render(AssemblyName assembly, INamedTypeSymbol type, List<SerializedProp> propList)
	{
		var serializerName = $"{type.Name}Serializer";
		var nestedTypeString = type.ToDisplayString(CustomSymbolDisplayFormats.NestedTypeName);

		var (primitives, nodes) = GetPropCollections(propList);

		var writer = new IndentedTextWriter(new StringWriter(), "\t");

		writer.WriteLine("#nullable enable");
		writer.WriteLine("// <auto-generated />");
		writer.BlankLine();

		WriteUsings(writer, type, propList);

		writer.BlankLine();
		writer.WriteLine("namespace GeneratedSerializers;");
		writer.BlankLine();

		writer.WriteLine("[GeneratedCode(\"{0}\", \"{1}\")]", assembly.Name, assembly.Version);
		writer.WriteLine("{0} class {1} : INodeSerializer<{2}>", SyntaxFacts.GetText(type.DeclaredAccessibility), serializerName, nestedTypeString);

		// Class body
		writer.BodyIndent(() =>
			{
				WriteChildSerializerFields(writer, propList);
				writer.BlankLine();
				WriteConstructor(writer, serializerName, propList, primitives, nodes);
				writer.BlankLine();
				WriteNodeSize(writer);
				writer.BlankLine();
				WriteNodeSizeForObject(writer, nestedTypeString, primitives, nodes);
				writer.BlankLine();
				WriteSerialize(writer, nestedTypeString, propList);
				writer.BlankLine();
				WriteDeserialize(writer, nestedTypeString, propList);
			}
		);

		return SourceText.From(writer.InnerWriter.ToString(), Encoding.UTF8);
	}

	private static void WriteUsings(IndentedTextWriter writer, INamedTypeSymbol typeSymbol, List<SerializedProp> propList)
	{
		var usings = new SortedSet<string>(new NamespaceComparer())
		{
			typeof(object).Namespace!,
			typeof(GeneratedCodeAttribute).Namespace!,
			"Pando.DataSources",
			typeSymbol.ContainingNamespace.ToDisplayString(CustomSymbolDisplayFormats.FullyQualifiedTypeName)
		};

		var binaryBuffersNs = typeof(BinaryPrimitives).Namespace!;
		foreach (var prop in propList)
		{
			if (prop.IsPrimitive)
			{
				usings.Add("Pando.Serialization.PrimitiveSerializers");
			}
			else
			{
				usings.Add("Pando.Serialization.NodeSerializers");
				usings.Add(binaryBuffersNs);
			}

			if (prop.Type.ContainingNamespace is not null)
			{
				usings.Add(prop.Type.ContainingNamespace.ToDisplayString(CustomSymbolDisplayFormats.FullyQualifiedTypeName));
			}
		}

		foreach (var u in usings)
		{
			if (u is null) continue;
			writer.WriteLine("using {0};", u);
		}
	}

	private static void WriteChildSerializerFields(IndentedTextWriter writer, List<SerializedProp> propList)
	{
		foreach (var prop in propList)
		{
			writer.WriteLine("private readonly {0} _{1};", prop.SerializerType.GenericName, prop.SerializerName);
		}
	}

	private static void WriteConstructor(
		IndentedTextWriter writer,
		string serializerName,
		List<SerializedProp> propList,
		List<SerializedProp> primitives,
		List<SerializedProp> nodes
	)
	{
		writer.WriteLine("public {0}(", serializerName);
		writer.DoIndent(() =>
			{
				for (var i = 0; i < propList.Count; i++)
				{
					var prop = propList[i];
					var comma = (i + 1 == propList.Count) ? string.Empty : ",";
					writer.WriteLine("{0} {1}{2}", prop.SerializerType.GenericName, prop.SerializerName, comma);
				}
			}
		);
		writer.WriteLine(")");

		writer.BodyIndent(() =>
			{
				foreach (var prop in propList)
				{
					writer.WriteLine("_{0} = {0};", prop.SerializerName);
				}

				writer.BlankLine();

				writer.WriteLine("int? size = 0;");

				foreach (var prop in primitives)
				{
					writer.WriteLine("size += _{0}.ByteCount;", prop.SerializerName);
				}

				writer.WriteLine("size += {0} * sizeof(ulong);", nodes.Count);

				writer.WriteLine("NodeSize = size;");
			}
		);
	}

	private static void WriteNodeSize(IndentedTextWriter writer)
	{
		writer.WriteLine("public int? NodeSize { get; }");
	}

	private static void WriteNodeSizeForObject(IndentedTextWriter writer, string nestedTypeString, List<SerializedProp> primitives,
		List<SerializedProp> nodes)
	{
		writer.WriteLine("public int NodeSizeForObject({0} obj)", nestedTypeString);
		writer.BodyIndent(() =>
			{
				writer.WriteLine("if (NodeSize is not null) return NodeSize.Value;");
				writer.BlankLine();

				// Calculate node size
				writer.WriteLine("int size = 0;");

				foreach (var prop in primitives)
				{
					writer.WriteLine("size += _{0}.ByteCountForValue(obj.{1});", prop.SerializerName, prop.Name);
				}

				writer.WriteLine("size += {0} * sizeof(ulong);", nodes.Count);

				writer.WriteLine("return size;");
			}
		);
	}

	private static void WriteSerialize(IndentedTextWriter writer, string nestedTypeString, List<SerializedProp> propList)
	{
		writer.WriteLine("public void Serialize({0} obj, Span<byte> writeBuffer, INodeDataSink dataSink)", nestedTypeString);
		writer.BodyIndent(() =>
			{
				var count = propList.Count;
				foreach (var prop in propList)
				{
					count--;
					if (prop.IsPrimitive)
					{
						writer.WriteLine("_{0}.Serialize(obj.{1}, ref writeBuffer);", prop.SerializerName, prop.Name);
					}
					else
					{
						writer.WriteLine("ulong {0}Hash = _{1}.SerializeToHash(obj.{2}, dataSink);",
							prop.CamelCaseName, prop.SerializerName, prop.Name
						);
						writer.WriteLine("BinaryPrimitives.WriteUInt64LittleEndian(writeBuffer[..sizeof(ulong)], {0}Hash);",
							prop.CamelCaseName
						);
						if (count > 0)
						{
							writer.WriteLine("writeBuffer = writeBuffer[sizeof(ulong)..];");
						}
					}

					if (count > 0)
					{
						writer.BlankLine();
					}
				}
			}
		);
	}

	private static void WriteDeserialize(IndentedTextWriter writer, string nestedTypeString, List<SerializedProp> propList)
	{
		writer.WriteLine("public {0} Deserialize(ReadOnlySpan<byte> readBuffer, INodeDataSource dataSource)", nestedTypeString);
		writer.BodyIndent(() =>
			{
				var count = propList.Count;
				foreach (var prop in propList)
				{
					count--;
					if (prop.IsPrimitive)
					{
						writer.WriteLine("var {0} = _{1}.Deserialize(ref readBuffer);", prop.CamelCaseName, prop.SerializerName);
					}
					else
					{
						writer.WriteLine("ulong {0}Hash = BinaryPrimitives.ReadUInt64LittleEndian(readBuffer[..sizeof(ulong)]);", prop.CamelCaseName);
						writer.WriteLine("var {0} = _{1}.DeserializeFromHash({0}Hash, dataSource);", prop.CamelCaseName, prop.SerializerName);
						if (count > 0)
						{
							writer.WriteLine("readBuffer = readBuffer[sizeof(ulong)..];");
						}
					}

					writer.BlankLine();
				}

				writer.WriteLine("return new {0}({1});", nestedTypeString, string.Join(", ", propList.Select(prop => prop.CamelCaseName)));
			}
		);
	}

	private static (List<SerializedProp> primitives, List<SerializedProp> nodes) GetPropCollections(List<SerializedProp> propList)
	{
		List<SerializedProp> primitives = new();
		List<SerializedProp> nodes = new();
		foreach (var prop in propList)
		{
			if (prop.IsPrimitive)
				primitives.Add(prop);
			else
				nodes.Add(prop);
		}

		return (primitives, nodes);
	}
}

internal class NamespaceComparer : IComparer<string>
{
	public int Compare(string x, string y)
	{
		var xIsSystem = x?.StartsWith("System");
		var yIsSystem = y?.StartsWith("System");
		if (xIsSystem is null || yIsSystem is null || xIsSystem == yIsSystem) return StringComparer.Ordinal.Compare(x, y);

		return xIsSystem.Value ? -1 : 1;
	}
}
